#ifndef PPU_PASS
#define PPU_PASS

include "mlir/Pass/PassBase.td"

def PPUSwitchBarFoo: Pass<"ppu-switch-bar-foo", "::mlir::ModuleOp"> {
  let summary = "Switches the name of a FuncOp named `bar` to `foo` and folds.";
  let description = [{
    Switches the name of a FuncOp named `bar` to `foo` and folds.
    ```
    func.func @bar() {
      return
    }
    // Gets transformed to:
    func.func @foo() {
      return
    }
    ```
  }];
}

#endif // PPU_PASS
